apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-add-cluster
spec:
  template:
    spec:
      containers:
      - name: argocd
        image: quay.io/argoproj/argocd:latest
        command: ["/usr/bin/env", "bash", "/kubeconfig/cluster_add.sh"]
        volumeMounts:
        - name: kubecontexts
          mountPath: /kubeconfig
          readOnly: true
        env:
        - name: KIND_CLUSTER_NAME
          value: replaceme
        - name: KIND_CLUSTER_LABEL_ARGS
          value: ""
        - name: KIND_ARGOCD_ADMIN_PASS
          valueFrom:
            secretKeyRef:
              name: argocd-initial-admin-secret
              key: password
      restartPolicy: Never
      volumes:
        - name: kubecontexts
          secret:
            secretName: kubecontexts
  backoffLimit: 1